# Generated by Django 4.0 on 2023-02-12 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_seller_nme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller_nme',
            new_name='seller_name',
        ),
    ]
